### ISSUE TITLE
Class load should have more suitable objects in "Class" class

### ISSUE THREAD

**Issue by AfonsoCostaVale** [JoaoAlmeida-dev/ADS_Project_3_Group11#4]
There are some members of the class "Class" that shouldn't be String.

**Comment by JoaoAlmeida-dev** [comment]
Most important Members that shouldn't be string are the beginningHour and endHour, the time of a class should be divided in "blocks" of 30min (as suggested by the professor) that way every class fits easily in the timeTable.

**Comment by AfonsoCostaVale** [comment]
Some changes were made but there maybe still some changes that must still be done

**Comment by AfonsoCostaVale** [comment]
The member capacity is a String but can be changed to int. The problem is that sometimes its empty, should i consider it as 0 or -1 if empty ? what is your opinion @JoaoAlmeida-dev ?

**Comment by JoaoAlmeida-dev** [comment]
maybe we should ask the prof, but for now we can keep it as a -1

**Comment by AfonsoCostaVale** [comment]
Solved on v1.0.0-alpha
